const SOLICITUDES_KEY = "ia-coop-mock-solicitudes";
const EVALUACIONES_KEY = "ia-coop-mock-evaluaciones";

export function seedMockData() {
  if (typeof window === "undefined") return;

  const already = localStorage.getItem(SOLICITUDES_KEY);
  if (already) return;

  const adminId = "mock-admindemo.com";
  const gestorId = "mock-gestordemo.com";
  const asociadoId = "mock-carlosdemo.com";

  const now = new Date();
  const solicitudes = [
    {
      $id: "mock-sol-001",
      asociadoId,
      montoSolicitado: 5000000,
      plazoMeses: 12,
      destino: "emprendimiento",
      estado: "pendiente",
      fechaSolicitud: new Date(now.getTime() - 86400000 * 2).toISOString(),
      metadata: {
        ingresoMensual: 2500000,
        fuenteIngreso: "empleado",
        gastosFijos: 1200000,
        personasACargo: 1,
        tieneOtrasDeudas: false,
        montoDeudas: 0,
        ahorraMensualmente: true,
        montoAhorro: 300000,
        antiguedadMeses: 18,
        participacionAsambleas: 3,
        consistenciaIngresos: 80,
        responsabilidadPagos: 65,
        compromisoCooperativo: 70,
        perfilEndeudamiento: 30,
        capacidadAhorro: 55,
      },
    },
    {
      $id: "mock-sol-002",
      asociadoId: gestorId,
      montoSolicitado: 8000000,
      plazoMeses: 24,
      destino: "vivienda",
      estado: "precalificado",
      fechaSolicitud: new Date(now.getTime() - 86400000 * 5).toISOString(),
      metadata: {
        ingresoMensual: 3200000,
        fuenteIngreso: "empleado",
        gastosFijos: 1500000,
        personasACargo: 2,
        tieneOtrasDeudas: true,
        montoDeudas: 500000,
        ahorraMensualmente: true,
        montoAhorro: 400000,
        antiguedadMeses: 36,
        participacionAsambleas: 5,
        consistenciaIngresos: 80,
        responsabilidadPagos: 70,
        compromisoCooperativo: 85,
        perfilEndeudamiento: 45,
        capacidadAhorro: 60,
      },
    },
    {
      $id: "mock-sol-003",
      asociadoId,
      montoSolicitado: 3000000,
      plazoMeses: 6,
      destino: "educacion",
      estado: "precalificado",
      fechaSolicitud: new Date(now.getTime() - 86400000 * 10).toISOString(),
      metadata: {
        ingresoMensual: 1800000,
        fuenteIngreso: "independiente",
        gastosFijos: 800000,
        personasACargo: 0,
        tieneOtrasDeudas: false,
        montoDeudas: 0,
        ahorraMensualmente: false,
        montoAhorro: 0,
        antiguedadMeses: 6,
        participacionAsambleas: 1,
        consistenciaIngresos: 60,
        responsabilidadPagos: 55,
        compromisoCooperativo: 40,
        perfilEndeudamiento: 25,
        capacidadAhorro: 30,
      },
    },
    {
      $id: "mock-sol-004",
      asociadoId,
      montoSolicitado: 12000000,
      plazoMeses: 48,
      destino: "vehiculo",
      estado: "aprobado",
      fechaSolicitud: new Date(now.getTime() - 86400000 * 30).toISOString(),
      metadata: {
        ingresoMensual: 4500000,
        fuenteIngreso: "empleado",
        gastosFijos: 2000000,
        personasACargo: 3,
        tieneOtrasDeudas: true,
        montoDeudas: 800000,
        ahorraMensualmente: true,
        montoAhorro: 500000,
        antiguedadMeses: 48,
        participacionAsambleas: 8,
        consistenciaIngresos: 80,
        responsabilidadPagos: 75,
        compromisoCooperativo: 90,
        perfilEndeudamiento: 50,
        capacidadAhorro: 65,
      },
    },
    {
      $id: "mock-sol-005",
      asociadoId: gestorId,
      montoSolicitado: 2000000,
      plazoMeses: 12,
      destino: "deudas",
      estado: "rechazado",
      fechaSolicitud: new Date(now.getTime() - 86400000 * 45).toISOString(),
      metadata: {
        ingresoMensual: 1200000,
        fuenteIngreso: "plataforma",
        gastosFijos: 900000,
        personasACargo: 2,
        tieneOtrasDeudas: true,
        montoDeudas: 1000000,
        ahorraMensualmente: false,
        montoAhorro: 0,
        antiguedadMeses: 3,
        participacionAsambleas: 0,
        consistenciaIngresos: 60,
        responsabilidadPagos: 30,
        compromisoCooperativo: 20,
        perfilEndeudamiento: 85,
        capacidadAhorro: 20,
      },
    },
  ];

  const evaluaciones = [
    {
      $id: "mock-eval-002",
      solicitudId: "mock-sol-002",
      asociadoId: gestorId,
      decision: "precalificado",
      puntajeRiesgo: 0.35,
      montoRecomendado: 6000000,
      consistenciaIngresos: 80,
      responsabilidadPagos: 70,
      compromisoCooperativo: 85,
      perfilEndeudamiento: 45,
      capacidadAhorro: 60,
      explicacionResumen: "Perfil crediticio favorable. El asociado tiene ingresos estables, buena capacidad de pago y una sólida relación con la cooperativa. Se recomienda aprobación con monto reducido para mantener perfil de riesgo bajo.",
      recomendaciones: ["Mantener el historial de ahorro", "Reducir deudas existentes antes de próximo crédito", "Seguir participando en asambleas"],
      fechaEvaluacion: new Date(now.getTime() - 86400000 * 4).toISOString(),
    },
    {
      $id: "mock-eval-003",
      solicitudId: "mock-sol-003",
      asociadoId,
      decision: "precalificado",
      puntajeRiesgo: 0.3,
      montoRecomendado: 2500000,
      consistenciaIngresos: 60,
      responsabilidadPagos: 55,
      compromisoCooperativo: 40,
      perfilEndeudamiento: 25,
      capacidadAhorro: 30,
      explicacionResumen: "Perfil crediticio aceptable. El asociado tiene ingresos moderados pero buena relación deuda/ingreso. Se recomienda aprobación condicionada a inicio de ahorro programado.",
      recomendaciones: ["Iniciar un ahorro mensual", "Aumentar participación en actividades cooperativas", "Considerar un plazo mayor para mejorar flujo de caja"],
      fechaEvaluacion: new Date(now.getTime() - 86400000 * 9).toISOString(),
    },
    {
      $id: "mock-eval-004",
      solicitudId: "mock-sol-004",
      asociadoId,
      decision: "aprobado",
      puntajeRiesgo: 0.25,
      montoRecomendado: 12000000,
      consistenciaIngresos: 80,
      responsabilidadPagos: 75,
      compromisoCooperativo: 90,
      perfilEndeudamiento: 50,
      capacidadAhorro: 65,
      explicacionResumen: "Excelente perfil crediticio. El asociado cuenta con ingresos sólidos, buena capacidad de ahorro y una trayectoria ejemplar en la cooperativa.",
      recomendaciones: ["Mantener el buen comportamiento de pago", "Seguir ahorrando mensualmente", "Considerar aumentar el monto en futuras solicitudes"],
      fechaEvaluacion: new Date(now.getTime() - 86400000 * 29).toISOString(),
    },
    {
      $id: "mock-eval-005",
      solicitudId: "mock-sol-005",
      asociadoId: gestorId,
      decision: "rechazado",
      puntajeRiesgo: 0.75,
      montoRecomendado: 0,
      consistenciaIngresos: 60,
      responsabilidadPagos: 30,
      compromisoCooperativo: 20,
      perfilEndeudamiento: 85,
      capacidadAhorro: 20,
      explicacionResumen: "Perfil crediticio desfavorable. Alta carga de deudas, baja capacidad de ahorro y poca participación cooperativa. Se recomienda rechazar la solicitud en este momento.",
      recomendaciones: ["Consolidar y reducir deudas existentes", "Iniciar un plan de ahorro", "Aumentar participación en la cooperativa", "Reintentar en 6 meses"],
      fechaEvaluacion: new Date(now.getTime() - 86400000 * 44).toISOString(),
    },
    {
      $id: "mock-eval-001",
      solicitudId: "mock-sol-001",
      asociadoId,
      decision: "pendiente",
      puntajeRiesgo: 0.4,
      montoRecomendado: 4000000,
      consistenciaIngresos: 80,
      responsabilidadPagos: 65,
      compromisoCooperativo: 70,
      perfilEndeudamiento: 30,
      capacidadAhorro: 55,
      explicacionResumen: "Solicitud en evaluación inicial. Se están verificando los datos proporcionados.",
      recomendaciones: [],
      fechaEvaluacion: new Date(now.getTime() - 86400000 * 1).toISOString(),
    },
  ];

  localStorage.setItem(SOLICITUDES_KEY, JSON.stringify(solicitudes));
  localStorage.setItem(EVALUACIONES_KEY, JSON.stringify(evaluaciones));
}
